project_id = "iukrokkltwqinixstuwy"

[functions.create-admin]
verify_jwt = false

[functions.ai-rewrite]
verify_jwt = false

[functions.news-discovery]
verify_jwt = false

[functions.api-status]
verify_jwt = false
